### ISSUE TITLE
Not working — NixOS gen61 x86_64

### ISSUE THREAD

**Issue by PoolloverNathan** [MidCoard/MinecraftNativesDownloader#1]
Running NixOS gen61 on x86_64. Downloader assumes amd64 and fails.
```nix
natives = util.execute "natives" ''
  #!${nixpkgs.bash}/bin/bash
  ${nixpkgs.jdk17}/bin/java -jar ${builtins.fetchurl https://github.com/MidCoard/MinecraftNativesDownloader/releases/download/1.1/MinecraftNativesDownloader-1.1.jar} --path ${fp /* this is downloaded version info path */}
  ls
  exit 1
'';
```
```
[nathan@nathanlaptopv:~/stuff/minix]$ nix build .#default.natives -o result.natives --impure 
warning: Git tree '/home/nathan/stuff/minix' is dirty
error: builder for '/nix/store/ism9a3hc95kicrlsw79q2hzv2wrnnlk6-natives.drv' failed with exit code 1;
       last 4 log lines:
       > Exception in thread "main" java.lang.IllegalArgumentException: Unknown architecture: amd64
       >        at top.focess.minecraft.minecraftnativesdownloader.platform.Architecture.parse(Architecture.java:25)
       >        at top.focess.minecraft.minecraftnativesdownloader.MinecraftNativesDownloader.main(MinecraftNativesDownloader.java:90)
       > /nix/store/qi9if4d5j6qw0xvf08kck2ajqg44dxy4-a: line 3: ls: command not found
       For full logs, run 'nix log /nix/store/ism9a3hc95kicrlsw79q2hzv2wrnnlk6-natives.drv'.

[nathan@nathanlaptopv:~/stuff/minix]$ uname -a
Linux nathanlaptopv 6.6.27 #1-NixOS SMP PREEMPT_DYNAMIC Sat Apr 13 11:07:41 UTC 2024 x86_64 GNU/Linux

[nathan@nathanlaptopv:~/stuff/minix]$ sudo nix-env -p /nix/var/nix/profiles/system --list-generations | tail -1
  61   2024-05-05 22:45:05   (current)```

**Comment by MidCoard** [comment]
Yes, amd64 should be the x86_64 architecture. But this repo is for the unsupported architecture Minecraft natives downloader, the lwjgl natives for x86_64 linux distribution are officially supported.

**Comment by MidCoard** [comment]
if you just want to use this tool to download natives conveniently, I'll fix this issue later.

**Comment by PoolloverNathan** [comment]
> Yes, amd64 should be the x86_64 architecture. But this repo is for the unsupported architecture Minecraft natives downloader, the lwjgl natives for x86_64 linux distribution are officially supported.

Oh, that makes sense. I'm writing a launcher and found a different way to download them automatically. Thank you!
